### ISSUE TITLE
missing fallbacks for UFO3 attributes

### ISSUE THREAD

**Issue by gferreira** [robotools/ufo2fdk#31]
Some new UFO3 font info attributes don’t have a fallback in `ufo2fdk.fontInfoData`.

Running the script below in RoboFont 2 will print the missing attributes:

```python
from ufo2fdk.fontInfoData import *

f = NewFont()
f.info.familyName = 'Hello'
f.info.styleName  = 'World'

for attr in sorted(f.info.asDict()):
    try:
        getAttrWithFallback(f.info, attr)
    except:
        print attr
```

```console
openTypeGaspRangeRecords
openTypeNameRecords
openTypeOS2WinAscent
openTypeOS2WinDescent
woffMajorVersion
woffMetadataCopyright
woffMetadataCredits
woffMetadataDescription
woffMetadataExtensions
woffMetadataLicense
woffMetadataLicensee
woffMetadataTrademark
woffMetadataUniqueID
woffMetadataVendor
woffMinorVersion
```

**Comment by typemytype** [comment]
`openTypeOS2WinAscent` and `openTypeOS2WinDescent` where RF issues

the rest should have some sort of a fallback in the infoData

**Comment by typemytype** [comment]
added here (my fork) see https://github.com/typemytype/ufo2fdk/commit/82ae9f11e480ab710a2669de12a9fcb42ff25937

**Comment by gferreira** [comment]
thanks!

(keeping the issue open until the change is merged)

**Comment by benkiel** [comment]
This looks merged. Closing.
