### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("*** Warning: FontTools needs the numpy library for some operations, see:")?

### ISSUE THREAD

**Issue by tom10271** [robotools/ufo2fdk#33]
K:\del\robofab-master\robofab-master>python setup.py install
  File "setup.py", line 15
    print "*** Warning: FontTools needs the numpy library for some operations, see:"
                                                                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("*** Warning: FontTools needs the numpy library for some operations, see:")?

**Comment by typemytype** [comment]
robofab is not py3 ready

**Comment by benkiel** [comment]
I think this is an issue for Robofab, which will never be py3, as it's archived. Closing
