### ISSUE TITLE
Add public.skipExportGlyphs handling

### ISSUE THREAD

**Issue by benkiel** [robotools/ufo2fdk#40]
See https://github.com/unified-font-object/ufo-spec/pull/84. This is in ufo2ft.

**Comment by typesupply** [comment]
I took a quick look and I think this will need to be done in two places:

1. [getGroups](https://github.com/robotools/ufo2fdk/blob/master/Lib/ufo2fdk/kernFeatureWriter.py#L92) Filter out the glyphs from groups.
2. [getPairs](https://github.com/robotools/ufo2fdk/blob/master/Lib/ufo2fdk/kernFeatureWriter.py#L110) Filter out the glyphs from kerning pairs.
